### PR TITLE
updated metadata for 015 and 024

### PR DESCRIPTION
**Pull request by Jeffrey-Young**

### CODE REVIEW

**Comment by mgrauer** [comment]
@Jeffrey-Young You've included the file metadata.json~, which is probably from your editor.  Can you remove this file?

Also, the json is hard to read and work with on one line.  Can you rebuild it with some whitespace?  If you copy the text of the json into a tool like jsonlint.com, you'll get better whitespacing, though of course there are other ways.

**Comment by mgrauer** [comment]
@Jeffrey-Young 

Did you make additions to the script that you want to add to this branch, or did the script work as it is here, and hence I can merge this branch?

**Comment by Jeffrey-Young** [comment]
I made a local copy of the update_metadata script and that was the one I used to update the metadata for a single subject. The script on this branch is the one that updates the metadata for every subject...the only change made was the addition of python 2.6 compliance.

**Comment by mgrauer** [comment]
Let's try to capture both of these scripts in GH.  Can you either modify the script so that it can do all the subjects or just one subject, or what is probably easier, at least upload your modified script under a different name with a bit of commenting explaining how to use it?

**Comment by Jeffrey-Young** [comment]
Just pushed up the individual subject update script

**Comment by mgrauer** [comment]
I'd like to see these scripts improved at some point, but this is fine for now.

I've captured that in #19.

**Pull request merged**
